# fly.toml app configuration file generated for ai-chatbot-wqzqmw on 2025-05-02T02:58:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-chatbot-wqzqmw'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
